### ISSUE TITLE
logout button cover title

### ISSUE THREAD

**Issue by ludovicgueth** [Epi-Tools/blihweb#1]
![capture d ecran 2018-01-02 a 17 13 39](https://user-images.githubusercontent.com/10414925/34490581-8f5c7c42-efe0-11e7-935c-425c8e7bb422.png)

**Comment by carlendev** [comment]
@ludovicgueth Thank's for the bug.
It should be fix.
Can you test if that's OK for you ?

**Comment by ludovicgueth** [comment]
fixed !
